###Create todo
POST http://localhost:8000/create
Content-Type: application/json


{
    "todo": "Coding in java"
}

###update todo
PATCH  http://localhost:8000/update/2
Content-Type: application/json


{
    //"_id": 2,
    "todo": "Coding in C"
}


### Get all todo
GET http://localhost:8000/all
Content-Type: application/application/x-www-form-urlencoded




###Get one to by id
GET http://localhost:8000/todo/2
Content-Type: application/application/x-www-form-urlencoded

### Delete todo
DELETE http://localhost:8000/delete/6
Content-Type: application/application/x-www-form-urlencoded